//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeTongji {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeTongji.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微同济用户协议.
        /// </summary>
        public static string About_AgreementLink {
            get {
                return ResourceManager.GetString("About_AgreementLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone 版本.
        /// </summary>
        public static string About_PlatformName {
            get {
                return ResourceManager.GetString("About_PlatformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 给WeTongji评分.
        /// </summary>
        public static string About_Rate {
            get {
                return ResourceManager.GetString("About_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问WeTongji官方网站.
        /// </summary>
        public static string About_ViewWebsite {
            get {
                return ResourceManager.GetString("About_ViewWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收藏.
        /// </summary>
        public static string Activity_AppBarFavoriteText {
            get {
                return ResourceManager.GetString("Activity_AppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 喜欢.
        /// </summary>
        public static string Activity_AppBarLikeText {
            get {
                return ResourceManager.GetString("Activity_AppBarLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参与.
        /// </summary>
        public static string Activity_AppBarParticipateText {
            get {
                return ResourceManager.GetString("Activity_AppBarParticipateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消收藏.
        /// </summary>
        public static string Activity_AppBarUnfavoriteText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnfavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消喜欢.
        /// </summary>
        public static string Activity_AppBarUnlikeText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnlikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消参与.
        /// </summary>
        public static string Activity_AppBarUnparticipateText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnparticipateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动详情.
        /// </summary>
        public static string Activity_EventDetails {
            get {
                return ResourceManager.GetString("Activity_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动配图.
        /// </summary>
        public static string Activity_EventIllustration {
            get {
                return ResourceManager.GetString("Activity_EventIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动介绍.
        /// </summary>
        public static string Activity_EventIntroduction {
            get {
                return ResourceManager.GetString("Activity_EventIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无图片信息.
        /// </summary>
        public static string Activity_NoIllustrationPrompt {
            get {
                return ResourceManager.GetString("Activity_NoIllustrationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布方.
        /// </summary>
        public static string Activity_Source {
            get {
                return ResourceManager.GetString("Activity_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户协议.
        /// </summary>
        public static string Agreement_PageTitle {
            get {
                return ResourceManager.GetString("Agreement_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string CampusInfo_AppBarRefreshText {
            get {
                return ResourceManager.GetString("CampusInfo_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周边推荐.
        /// </summary>
        public static string CampusInfo_AroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_AroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 票.
        /// </summary>
        public static string CampusInfo_AroundNewsWithTicketPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_AroundNewsWithTicketPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团体通知.
        /// </summary>
        public static string CampusInfo_ClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_ClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“周边推荐”.
        /// </summary>
        public static string CampusInfo_LoadingAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“团体通知”.
        /// </summary>
        public static string CampusInfo_LoadingClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“周边推荐”，请稍后....
        /// </summary>
        public static string CampusInfo_LoadingMoreAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“团体通知”，请稍后....
        /// </summary>
        public static string CampusInfo_LoadingMoreClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“校务通知”，请稍后....
        /// </summary>
        public static string CampusInfo_LoadingMoreOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“同济动态”，请稍后....
        /// </summary>
        public static string CampusInfo_LoadingMoreTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“校务通知”.
        /// </summary>
        public static string CampusInfo_LoadingOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载“同济动态”.
        /// </summary>
        public static string CampusInfo_LoadingTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多“周边推荐”.
        /// </summary>
        public static string CampusInfo_LoadMoreAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多“团体通知”.
        /// </summary>
        public static string CampusInfo_LoadMoreClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多“校务通知”.
        /// </summary>
        public static string CampusInfo_LoadMoreOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多“同济动态”.
        /// </summary>
        public static string CampusInfo_LoadMoreTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“周边推荐”信息.
        /// </summary>
        public static string CampusInfo_NoAroundNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoAroundNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“团体通知”信息.
        /// </summary>
        public static string CampusInfo_NoClubNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoClubNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“团体通知”信息.
        /// </summary>
        public static string CampusInfo_NoOfficialNotesPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoOfficialNotesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“同济动态”信息.
        /// </summary>
        public static string CampusInfo_NoTongjiNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoTongjiNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校务通知.
        /// </summary>
        public static string CampusInfo_OfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_OfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校园资讯.
        /// </summary>
        public static string CampusInfo_PageTitle {
            get {
                return ResourceManager.GetString("CampusInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同济动态.
        /// </summary>
        public static string CampusInfo_TongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_TongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收藏.
        /// </summary>
        public static string Common_AppBarFavoriteText {
            get {
                return ResourceManager.GetString("Common_AppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 喜欢.
        /// </summary>
        public static string Common_AppBarLikeText {
            get {
                return ResourceManager.GetString("Common_AppBarLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消收藏.
        /// </summary>
        public static string Common_AppBarUnfavoriteText {
            get {
                return ResourceManager.GetString("Common_AppBarUnfavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消喜欢.
        /// </summary>
        public static string Common_AppBarUnlikeText {
            get {
                return ResourceManager.GetString("Common_AppBarUnlikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确认要退出微同济吗？.
        /// </summary>
        public static string Common_ExitAppPromptContent {
            get {
                return ResourceManager.GetString("Common_ExitAppPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请重试.
        /// </summary>
        public static string Common_FailurePrompt {
            get {
                return ResourceManager.GetString("Common_FailurePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载图片....
        /// </summary>
        public static string Common_LoadingPicture {
            get {
                return ResourceManager.GetString("Common_LoadingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （图片加载失败，请点击重试）.
        /// </summary>
        public static string Common_LoadPictureFailedPrompt {
            get {
                return ResourceManager.GetString("Common_LoadPictureFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请登录后再试.
        /// </summary>
        public static string Common_LogInFirstPrompt {
            get {
                return ResourceManager.GetString("Common_LogInFirstPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Common_Prompt {
            get {
                return ResourceManager.GetString("Common_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您是否在其他客户端中登录过？请重新登录.
        /// </summary>
        public static string Common_SignInOnOtherPlatformPrompt {
            get {
                return ResourceManager.GetString("Common_SignInOnOtherPlatformPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程详情.
        /// </summary>
        public static string CourseDetail_CourseHeader {
            get {
                return ResourceManager.GetString("CourseDetail_CourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课号.
        /// </summary>
        public static string CourseDetail_CourseNO {
            get {
                return ResourceManager.GetString("CourseDetail_CourseNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考试安排.
        /// </summary>
        public static string CourseDetail_ExamHeader {
            get {
                return ResourceManager.GetString("CourseDetail_ExamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学时.
        /// </summary>
        public static string CourseDetail_Hours {
            get {
                return ResourceManager.GetString("CourseDetail_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载课程详情.
        /// </summary>
        public static string CourseDetail_LoadingCourseDetail {
            get {
                return ResourceManager.GetString("CourseDetail_LoadingCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载考试安排.
        /// </summary>
        public static string CourseDetail_LoadingExam {
            get {
                return ResourceManager.GetString("CourseDetail_LoadingExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地点.
        /// </summary>
        public static string CourseDetail_Location {
            get {
                return ResourceManager.GetString("CourseDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无课程详情.
        /// </summary>
        public static string CourseDetail_NoCoursePrompt {
            get {
                return ResourceManager.GetString("CourseDetail_NoCoursePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无考试安排.
        /// </summary>
        public static string CourseDetail_NoExamPrompt {
            get {
                return ResourceManager.GetString("CourseDetail_NoExamPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学分.
        /// </summary>
        public static string CourseDetail_Points {
            get {
                return ResourceManager.GetString("CourseDetail_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 老师.
        /// </summary>
        public static string CourseDetail_Teacher {
            get {
                return ResourceManager.GetString("CourseDetail_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        public static string CourseDetail_Time {
            get {
                return ResourceManager.GetString("CourseDetail_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误,请重新输入.
        /// </summary>
        public static string MainPage_AccountPasswordDismatchPrompt {
            get {
                return ResourceManager.GetString("MainPage_AccountPasswordDismatchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐活动.
        /// </summary>
        public static string MainPage_Activities {
            get {
                return ResourceManager.GetString("MainPage_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;活动即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_ActivityExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ActivityExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒.
        /// </summary>
        public static string MainPage_Alarms {
            get {
                return ResourceManager.GetString("MainPage_Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string MainPage_AppBarAboutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户反馈.
        /// </summary>
        public static string MainPage_AppBarFeedbackText {
            get {
                return ResourceManager.GetString("MainPage_AppBarFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最火活动.
        /// </summary>
        public static string MainPage_AppBarHotEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarHotEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新活动.
        /// </summary>
        public static string MainPage_AppBarLatestEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarLatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string MainPage_AppBarLoginText {
            get {
                return ResourceManager.GetString("MainPage_AppBarLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近活动.
        /// </summary>
        public static string MainPage_AppBarRecentEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarRecentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string MainPage_AppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string MainPage_AppBarRegisterText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MainPage_AppBarSettingsText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件分享给好友.
        /// </summary>
        public static string MainPage_AppBarShareToFriendsByMail {
            get {
                return ResourceManager.GetString("MainPage_AppBarShareToFriendsByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销.
        /// </summary>
        public static string MainPage_AppBarSignOutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看历史.
        /// </summary>
        public static string MainPage_AppBarViewAllPeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_AppBarViewAllPeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周边推荐.
        /// </summary>
        public static string MainPage_AroundNews {
            get {
                return ResourceManager.GetString("MainPage_AroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校园资讯.
        /// </summary>
        public static string MainPage_CampusInfo {
            get {
                return ResourceManager.GetString("MainPage_CampusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团体通知.
        /// </summary>
        public static string MainPage_ClubNews {
            get {
                return ResourceManager.GetString("MainPage_ClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败，请重试.
        /// </summary>
        public static string MainPage_CommonLoginFailedPrompt {
            get {
                return ResourceManager.GetString("MainPage_CommonLoginFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定想要注销账号？.
        /// </summary>
        public static string MainPage_ConfirmSignOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_ConfirmSignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;课程即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_CourseExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_CourseExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string MainPage_EnterPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入学号.
        /// </summary>
        public static string MainPage_EnterStudentNOPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterStudentNOPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;考试即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_ExamExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ExamExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态.
        /// </summary>
        public static string MainPage_Feed {
            get {
                return ResourceManager.GetString("MainPage_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码？.
        /// </summary>
        public static string MainPage_ForgotPasswordLink {
            get {
                return ResourceManager.GetString("MainPage_ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不符合要求,请重新输入.
        /// </summary>
        public static string MainPage_InvalidPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_InvalidPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中.
        /// </summary>
        public static string MainPage_LoadingAlarms {
            get {
                return ResourceManager.GetString("MainPage_LoadingAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载更多活动....
        /// </summary>
        public static string MainPage_LoadingMoreEvents {
            get {
                return ResourceManager.GetString("MainPage_LoadingMoreEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多活动.
        /// </summary>
        public static string MainPage_LoadMoreActivities {
            get {
                return ResourceManager.GetString("MainPage_LoadMoreActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录超时,请重试.
        /// </summary>
        public static string MainPage_LoginTimeOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_LoginTimeOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的日程.
        /// </summary>
        public static string MainPage_MyAgenda {
            get {
                return ResourceManager.GetString("MainPage_MyAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的收藏.
        /// </summary>
        public static string MainPage_MyFavorite {
            get {
                return ResourceManager.GetString("MainPage_MyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号不存在,请重试.
        /// </summary>
        public static string MainPage_NoAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“推荐活动”信息.
        /// </summary>
        public static string MainPage_NoActivitiesPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoActivitiesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今天.
        /// </summary>
        public static string MainPage_NoArrangementTodayFirstLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodayFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有安排.
        /// </summary>
        public static string MainPage_NoArrangementTodaySecondLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodaySecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“每周人物”信息.
        /// </summary>
        public static string MainPage_NoPeopleOfWeekPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoPeopleOfWeekPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号未激活,请重试.
        /// </summary>
        public static string MainPage_NotActivatedAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotActivatedAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户没有注册,请重试.
        /// </summary>
        public static string MainPage_NotRegisteredPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotRegisteredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校务通知.
        /// </summary>
        public static string MainPage_OfficialNotes {
            get {
                return ResourceManager.GetString("MainPage_OfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参与.
        /// </summary>
        public static string MainPage_Participants {
            get {
                return ResourceManager.GetString("MainPage_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string MainPage_Password {
            get {
                return ResourceManager.GetString("MainPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每周人物.
        /// </summary>
        public static string MainPage_PeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_PeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我正在使用微同济-同济大学专属校园移动应用，帮助管理我的大学日程，推送校内校外的大小活动，不再错过任何一个精彩的活动，快点和我一起去下载(http://we.tongji.edu.cn).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailBody {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐使用WeTongji(Windows Phone版).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailSubject {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string MainPage_StudentNO {
            get {
                return ResourceManager.GetString("MainPage_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同济动态.
        /// </summary>
        public static string MainPage_TongjiNews {
            get {
                return ResourceManager.GetString("MainPage_TongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我正在{0} {1}上使用微同济Windows Phone v{2}，.
        /// </summary>
        public static string MainPage_UserFeedBackEmailBodyTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [用户反馈]微同济Windows Phone v{0}.
        /// </summary>
        public static string MainPage_UserFeedBackEmailSubjectTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看详情.
        /// </summary>
        public static string MainPage_ViewPeopleOfWeekDetail {
            get {
                return ResourceManager.GetString("MainPage_ViewPeopleOfWeekDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}，欢迎再次使用微同济~.
        /// </summary>
        public static string Toast_AutoLoginSucceededPromptTemplate {
            get {
                return ResourceManager.GetString("Toast_AutoLoginSucceededPromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络异常，请稍后再试.
        /// </summary>
        public static string Toast_NetworkErrorPrompt {
            get {
                return ResourceManager.GetString("Toast_NetworkErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恭喜，登录成功~.
        /// </summary>
        public static string Toast_SignInSucceededPrompt {
            get {
                return ResourceManager.GetString("Toast_SignInSucceededPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        public static string Toast_Success {
            get {
                return ResourceManager.GetString("Toast_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微同济官方主页.
        /// </summary>
        public static string ViewOfficialWebsite_PageTitle {
            get {
                return ResourceManager.GetString("ViewOfficialWebsite_PageTitle", resourceCulture);
            }
        }
    }
}
