//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeTongji {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeTongji.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确认要退出微同济吗？.
        /// </summary>
        public static string Common_ExitAppPromptContent {
            get {
                return ResourceManager.GetString("Common_ExitAppPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Common_Prompt {
            get {
                return ResourceManager.GetString("Common_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误,请重新输入.
        /// </summary>
        public static string MainPage_AccountPasswordDismatchPrompt {
            get {
                return ResourceManager.GetString("MainPage_AccountPasswordDismatchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐活动.
        /// </summary>
        public static string MainPage_Activities {
            get {
                return ResourceManager.GetString("MainPage_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;活动即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_ActivityExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ActivityExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒.
        /// </summary>
        public static string MainPage_Alarms {
            get {
                return ResourceManager.GetString("MainPage_Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string MainPage_AppBarAboutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户反馈.
        /// </summary>
        public static string MainPage_AppBarFeedbackText {
            get {
                return ResourceManager.GetString("MainPage_AppBarFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最火活动.
        /// </summary>
        public static string MainPage_AppBarHotEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarHotEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新活动.
        /// </summary>
        public static string MainPage_AppBarLatestEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarLatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string MainPage_AppBarLoginText {
            get {
                return ResourceManager.GetString("MainPage_AppBarLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近活动.
        /// </summary>
        public static string MainPage_AppBarRecentEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarRecentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string MainPage_AppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string MainPage_AppBarRegisterText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MainPage_AppBarSettingsText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件分享给好友.
        /// </summary>
        public static string MainPage_AppBarShareToFriendsByMail {
            get {
                return ResourceManager.GetString("MainPage_AppBarShareToFriendsByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销.
        /// </summary>
        public static string MainPage_AppBarSignOutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看历史.
        /// </summary>
        public static string MainPage_AppBarViewAllPeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_AppBarViewAllPeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周边推荐.
        /// </summary>
        public static string MainPage_AroundNews {
            get {
                return ResourceManager.GetString("MainPage_AroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校园资讯.
        /// </summary>
        public static string MainPage_CampusInfo {
            get {
                return ResourceManager.GetString("MainPage_CampusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团体通知.
        /// </summary>
        public static string MainPage_ClubNews {
            get {
                return ResourceManager.GetString("MainPage_ClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败，请重试.
        /// </summary>
        public static string MainPage_CommonLoginFailedPrompt {
            get {
                return ResourceManager.GetString("MainPage_CommonLoginFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定想要注销账号？.
        /// </summary>
        public static string MainPage_ConfirmSignOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_ConfirmSignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;课程即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_CourseExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_CourseExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string MainPage_EnterPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入学号.
        /// </summary>
        public static string MainPage_EnterStudentNOPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterStudentNOPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在是{0}，\&quot;{1}\&quot;考试即将在{2}分钟后开始，请注意安排时间~.
        /// </summary>
        public static string MainPage_ExamExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ExamExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态.
        /// </summary>
        public static string MainPage_Feed {
            get {
                return ResourceManager.GetString("MainPage_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码？.
        /// </summary>
        public static string MainPage_ForgotPasswordLink {
            get {
                return ResourceManager.GetString("MainPage_ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不符合要求,请重新输入.
        /// </summary>
        public static string MainPage_InvalidPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_InvalidPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中.
        /// </summary>
        public static string MainPage_LoadingAlarms {
            get {
                return ResourceManager.GetString("MainPage_LoadingAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载更多活动....
        /// </summary>
        public static string MainPage_LoadingMoreEvents {
            get {
                return ResourceManager.GetString("MainPage_LoadingMoreEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多活动.
        /// </summary>
        public static string MainPage_LoadMoreActivities {
            get {
                return ResourceManager.GetString("MainPage_LoadMoreActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录超时,请重试.
        /// </summary>
        public static string MainPage_LoginTimeOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_LoginTimeOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的日程.
        /// </summary>
        public static string MainPage_MyAgenda {
            get {
                return ResourceManager.GetString("MainPage_MyAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的收藏.
        /// </summary>
        public static string MainPage_MyFavorite {
            get {
                return ResourceManager.GetString("MainPage_MyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号不存在,请重试.
        /// </summary>
        public static string MainPage_NoAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“推荐活动”信息.
        /// </summary>
        public static string MainPage_NoActivitiesPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoActivitiesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今天.
        /// </summary>
        public static string MainPage_NoArrangementTodayFirstLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodayFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有安排.
        /// </summary>
        public static string MainPage_NoArrangementTodaySecondLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodaySecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无“每周人物”信息.
        /// </summary>
        public static string MainPage_NoPeopleOfWeekPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoPeopleOfWeekPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号未激活,请重试.
        /// </summary>
        public static string MainPage_NotActivatedAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotActivatedAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户没有注册,请重试.
        /// </summary>
        public static string MainPage_NotRegisteredPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotRegisteredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校务通知.
        /// </summary>
        public static string MainPage_OfficialNotes {
            get {
                return ResourceManager.GetString("MainPage_OfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参与.
        /// </summary>
        public static string MainPage_Participants {
            get {
                return ResourceManager.GetString("MainPage_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string MainPage_Password {
            get {
                return ResourceManager.GetString("MainPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每周人物.
        /// </summary>
        public static string MainPage_PeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_PeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我正在使用微同济-同济大学专属校园移动应用，帮助管理我的大学日程，推送校内校外的大小活动，不再错过任何一个精彩的活动，快点和我一起去下载(http://we.tongji.edu.cn).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailBody {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐使用WeTongji(Windows Phone版).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailSubject {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string MainPage_StudentNO {
            get {
                return ResourceManager.GetString("MainPage_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同济动态.
        /// </summary>
        public static string MainPage_TongjiNews {
            get {
                return ResourceManager.GetString("MainPage_TongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我正在{0} {1}上使用微同济Windows Phone v{2}，.
        /// </summary>
        public static string MainPage_UserFeedBackEmailBodyTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [用户反馈]微同济Windows Phone v{0}.
        /// </summary>
        public static string MainPage_UserFeedBackEmailSubjectTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看详情.
        /// </summary>
        public static string MainPage_ViewPeopleOfWeekDetail {
            get {
                return ResourceManager.GetString("MainPage_ViewPeopleOfWeekDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}，欢迎再次使用微同济~.
        /// </summary>
        public static string Toast_AutoLoginSucceededPromptTemplate {
            get {
                return ResourceManager.GetString("Toast_AutoLoginSucceededPromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络异常，请稍后再试.
        /// </summary>
        public static string Toast_NetworkErrorPrompt {
            get {
                return ResourceManager.GetString("Toast_NetworkErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恭喜，登录成功~.
        /// </summary>
        public static string Toast_SignInSucceededPrompt {
            get {
                return ResourceManager.GetString("Toast_SignInSucceededPrompt", resourceCulture);
            }
        }
    }
}
